apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 1.8.6
appVersion: 1.8.6
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
