apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 1.9.0
appVersion: 1.9.0
dependencies:
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm

  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
